# Generated by Django 3.2 on 2021-04-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='images_url',
        ),
        migrations.AddField(
            model_name='product',
            name='designer',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
